BASE = "-1001737980489"             # MAIN BASE GROUP, BOT WILL SEND LOG MESSAGES HERE
FFMPEG = "-1001737980489"           # FFMPEG FDK FILES STORED IN A CHANNEL, ITS ID
DESTINATION = "-1001737980489"      # ID OF CHANNEL/GROUP WHERE ALL OUTPUT FILES ARE SENT
FFMPEGID = "2 3 4"                  # MSG ID OF THE FFMPEG EXECUTABLES IN THE FFMPEG CHANNELS
FFMPEGCMD = "5"                     # MSG ID OF THE FFMPEG CMD THAT YOU WANT TO EXECUTE.
# IN YOUR CUSTOM COMMAND, FILE NAME SHOULD BE MENTIONED AS "./downloads/[FILE]"" AND OUTPUT FILE AS "./downloads/[AG] [FILE]" ONLY.
